In [19]:
#必要パッケージの取り込み
import pandas as pd
import statsmodels.api as sm 

#データの読み込み
data = "./data/Economic Data - 9 Countries (1980-2020).csv"

df = pd.read_csv(data)

#表示(確認)
df

,stock index,country,area,dummy,year,index price,log_indexprice,inflationrate,oil prices,exchange_rate,gdppercent,percapitaincome,unemploymentrate,manufacturingoutput,tradebalance,USTreasury
0,NASDAQ,United States of America,America,1,1980,168.61,2.23,0.14,21.59,1.00,0.09,12575.0,0.07,NaN,-13.06,0.11
1,NASDAQ,United States of America,America,1,1981,203.15,2.31,0.10,31.77,1.00,0.12,13976.0,0.08,NaN,-12.52,0.14
2,NASDAQ,United States of America,America,1,1982,188.98,2.28,0.06,28.52,1.00,0.04,14434.0,0.10,NaN,-19.97,0.13
3,NASDAQ,United States of America,America,1,1983,285.43,2.46,0.03,26.19,1.00,0.09,15544.0,0.10,NaN,-51.64,0.11
4,NASDAQ,United States of America,America,1,1984,248.89,2.40,0.04,25.88,1.00,0.11,17121.0,0.08,NaN,-102.73,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,IEX 35,Spain,Europe,1,2016,9352.10,3.97,NaN,51.97,1.11,0.03,26523.0,0.20,139.01,49.16,0.02
365,IEX 35,Spain,Europe,1,2017,10043.90,4.00,0.02,57.88,1.13,0.03,28170.0,0.17,148.80,47.33,0.02
366,IEX 35,Spain,Europe,1,2018,8539.90,3.93,0.02,49.52,1.18,0.02,30389.0,0.15,158.33,38.70,0.03
367,IEX 35,Spain,Europe,1,2019,9549.20,3.98,0.01,59.88,1.12,0.02,29565.0,0.14,155.49,41.94,0.02
368,IEX 35,Spain,Europe,1,2020,8073.70,3.91,NaN,47.02,1.14,-0.11,27057.0,0.16,143.05,19.10,0.01

In [20]:
#countryとyearを列の前に
df = df.set_index(['country', 'year'])

#表示(確認)
df

                              stock index     area  dummy  index price  \
country                  year
United States of America 1980      NASDAQ  America      1       168.61
                         1981      NASDAQ  America      1       203.15
                         1982      NASDAQ  America      1       188.98
                         1983      NASDAQ  America      1       285.43
                         1984      NASDAQ  America      1       248.89
...                                   ...      ...    ...          ...
Spain                    2016      IEX 35   Europe      1      9352.10
                         2017      IEX 35   Europe      1     10043.90
                         2018      IEX 35   Europe      1      8539.90
                         2019      IEX 35   Europe      1      9549.20
                         2020      IEX 35   Europe      1      8073.70

                               log_indexprice  inflationrate  oil prices  \
country                  year
United States of America 1980            2.23           0.14       21.59
                         1981            2.31           0.10       31.77
                         1982            2.28           0.06       28.52
                         1983            2.46           0.03       26.19
                         1984            2.40           0.04       25.88
...                                       ...            ...         ...
Spain                    2016            3.97            NaN       51.97
                         2017            4.00           0.02       57.88
                         2018            3.93           0.02       49.52
                         2019            3.98           0.01       59.88
                         2020            3.91            NaN       47.02

                               exchange_rate  gdppercent  percapitaincome  \
country                  year
United States of America 1980           1.00        0.09          12575.0
                         1981           1.00        0.12          13976.0
                         1982           1.00        0.04          14434.0
                         1983           1.00        0.09          15544.0
                         1984           1.00        0.11          17121.0
...                                      ...         ...              ...
Spain                    2016           1.11        0.03          26523.0
                         2017           1.13        0.03          28170.0
                         2018           1.18        0.02          30389.0
                         2019           1.12        0.02          29565.0
                         2020           1.14       -0.11          27057.0

                               unemploymentrate  manufacturingoutput  \
country                  year
United States of America 1980              0.07                  NaN
                         1981              0.08                  NaN
                         1982              0.10                  NaN
                         1983              0.10                  NaN
                         1984              0.08                  NaN
...                                         ...                  ...
Spain                    2016              0.20               139.01
                         2017              0.17               148.80
                         2018              0.15               158.33
                         2019              0.14               155.49
                         2020              0.16               143.05

                               tradebalance  USTreasury
country                  year
United States of America 1980        -13.06        0.11
                         1981        -12.52        0.14
                         1982        -19.97        0.13
                         1983        -51.64        0.11
                         1984       -102.73        0.12
...                                     ...         ...
Spain                    2016         49.16        0.02
                         2017         47.33        0.02
                         2018         38.70        0.03
                         2019         41.94        0.02
                         2020         19.10        0.01

[369 rows x 14 columns]

In [21]:
#Pooled OLS
from linearmodels import PooledOLS
exog_vars=['unemploymentrate','percapitaincome'] 
mod=PooledOLS(df.gdppercent,sm.add_constant(df[exog_vars])) 
pooled_res = mod.fit()

#表示
print(pooled_res)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:             gdppercent   R-squared:                        0.3690
Estimator:                  PooledOLS   R-squared (Between):              0.6675
No. Observations:                 329   R-squared (Within):               0.1282
Date:                Sat, Nov 05 2022   R-squared (Overall):              0.3690
Time:                        23:32:34   Log-likelihood                    690.02
Cov. Estimator:            Unadjusted
                                        F-statistic:                      95.339
Entities:                           9   P-value                           0.0000
Avg Obs:                       36.556   Distribution:                   F(2,326)
Min Obs:                       30.000
Max Obs:                       41.000   F-statistic (robust):             95.339
                                        P-value                           0.0000
Time periods:                      41   Distribution:                   F(2,326)
Avg Obs:                       8.0244
Min Obs:                       5.0000
Max Obs:                       9.0000

                                Parameter Estimates
====================================================================================
                  Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------
const                0.0800     0.0037     21.493     0.0000      0.0726      0.0873
unemploymentrate    -0.2878     0.0379    -7.5901     0.0000     -0.3625     -0.2132
percapitaincome  -1.118e-06  9.479e-08    -11.793     0.0000  -1.304e-06  -9.313e-07
====================================================================================

/opt/anaconda3/lib/python3.9/site-packages/linearmodels/panel/model.py:854: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

In [22]:
#固定効果モデル
from linearmodels import PanelOLS
exog_vars=['unemploymentrate','percapitaincome'] 
mod=PanelOLS(df.gdppercent,sm.add_constant(df[exog_vars])) 
fe_res = mod.fit()

#表示
print(fe_res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:             gdppercent   R-squared:                        0.3690
Estimator:                   PanelOLS   R-squared (Between):              0.6675
No. Observations:                 329   R-squared (Within):               0.1282
Date:                Sat, Nov 05 2022   R-squared (Overall):              0.3690
Time:                        23:32:36   Log-likelihood                    690.02
Cov. Estimator:            Unadjusted
                                        F-statistic:                      95.339
Entities:                           9   P-value                           0.0000
Avg Obs:                       36.556   Distribution:                   F(2,326)
Min Obs:                       30.000
Max Obs:                       41.000   F-statistic (robust):             95.339
                                        P-value                           0.0000
Time periods:                      41   Distribution:                   F(2,326)
Avg Obs:                       8.0244
Min Obs:                       5.0000
Max Obs:                       9.0000

                                Parameter Estimates
====================================================================================
                  Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------
const                0.0800     0.0037     21.493     0.0000      0.0726      0.0873
unemploymentrate    -0.2878     0.0379    -7.5901     0.0000     -0.3625     -0.2132
percapitaincome  -1.118e-06  9.479e-08    -11.793     0.0000  -1.304e-06  -9.313e-07
====================================================================================

/opt/anaconda3/lib/python3.9/site-packages/linearmodels/panel/model.py:1183: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

In [23]:
#変動効果モデル
from linearmodels import RandomEffects
exog_vars=['unemploymentrate','percapitaincome'] 
mod=RandomEffects(df.gdppercent,sm.add_constant(df[exog_vars])) 
re_res = mod.fit()

#表示
print(re_res)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:             gdppercent   R-squared:                        0.1650
Estimator:              RandomEffects   R-squared (Between):              0.6085
No. Observations:                 329   R-squared (Within):               0.1451
Date:                Sat, Nov 05 2022   R-squared (Overall):              0.3509
Time:                        23:32:39   Log-likelihood                    731.70
Cov. Estimator:            Unadjusted
                                        F-statistic:                      32.205
Entities:                           9   P-value                           0.0000
Avg Obs:                       36.556   Distribution:                   F(2,326)
Min Obs:                       30.000
Max Obs:                       41.000   F-statistic (robust):             32.897
                                        P-value                           0.0000
Time periods:                      41   Distribution:                   F(2,326)
Avg Obs:                       8.0244
Min Obs:                       5.0000
Max Obs:                       9.0000

                                Parameter Estimates
====================================================================================
                  Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------
const                0.0698     0.0075     9.2687     0.0000      0.0550      0.0846
unemploymentrate    -0.2227     0.0619    -3.5988     0.0004     -0.3444     -0.1009
percapitaincome  -8.744e-07   1.15e-07    -7.6027     0.0000  -1.101e-06  -6.481e-07
====================================================================================

/opt/anaconda3/lib/python3.9/site-packages/linearmodels/panel/model.py:2574: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

In [24]:
#Pooled OLS（Pooled）,固定効果モデル(FE),変動効果モデル(RE)の比較
from linearmodels.panel import compare 

#表示
print(compare({'Pooled':pooled_res,'FE':fe_res,'RE':re_res}))

                        Model Comparison
===============================================================
                            Pooled           FE              RE
---------------------------------------------------------------
Dep. Variable           gdppercent   gdppercent      gdppercent
Estimator                PooledOLS     PanelOLS   RandomEffects
No. Observations               329          329             329
Cov. Est.               Unadjusted   Unadjusted      Unadjusted
R-squared                   0.3690       0.3690          0.1650
R-Squared (Within)          0.1282       0.1282          0.1451
R-Squared (Between)         0.6675       0.6675          0.6085
R-Squared (Overall)         0.3690       0.3690          0.3509
F-statistic                 95.339       95.339          32.205
P-value (F-stat)            0.0000       0.0000          0.0000
===================== ============ ============ ===============
const                       0.0800       0.0800          0.0698
                          (21.493)     (21.493)        (9.2687)
unemploymentrate           -0.2878      -0.2878         -0.2227
                         (-7.5901)    (-7.5901)       (-3.5988)
percapitaincome         -1.118e-06   -1.118e-06      -8.744e-07
                         (-11.793)    (-11.793)       (-7.6027)
---------------------------------------------------------------

T-stats reported in parentheses